name: Black formatter check

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]


jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
      with:
        args: " --check --target-version py36 --line-length 120 --skip-string-normalization --exclude '(migrations|urls\.py)' stregsystem stregreport kiosk"

